CREATE DATABASE RaceDayDB;
GO

USE RaceDayDB;
GO
DROP TABLE IF EXISTS RESULT;
DROP TABLE IF EXISTS ENROLMENT;
DROP TABLE IF EXISTS EVENTCATEGORY;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS [USER];
GO
CREATE TABLE [USER] (
    UserID VARCHAR(50) PRIMARY KEY,
    FirstName VARCHAR(100) NOT NULL,
    LastName VARCHAR(100) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL CHECK (Role IN ('Organiser', 'Participant'))
);
CREATE TABLE EVENT (
    EventID VARCHAR(50) PRIMARY KEY,
    OrganiserID VARCHAR(50) NOT NULL,
    EventName VARCHAR(200) NOT NULL,
    Description VARCHAR(MAX),
    EventDate DATE NOT NULL,
    Location VARCHAR(200) NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'Upcoming',

    CONSTRAINT FK_Event_Organiser 
        FOREIGN KEY (OrganiserID) REFERENCES [USER](UserID)
);
CREATE TABLE CATEGORY (
    CategoryID VARCHAR(50) PRIMARY KEY,
    CategoryName VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(MAX)
);
CREATE TABLE EVENTCATEGORY (
    EventCategoryID VARCHAR(50) PRIMARY KEY,
    EventID VARCHAR(50) NOT NULL,
    CategoryID VARCHAR(50) NOT NULL,
    EntryFee DECIMAL(10, 2) NOT NULL,
    MaxParticipants INT NOT NULL,

    CONSTRAINT FK_EventCategory_Event 
        FOREIGN KEY (EventID) REFERENCES EVENT(EventID) ON DELETE CASCADE,

    CONSTRAINT FK_EventCategory_Category 
        FOREIGN KEY (CategoryID) REFERENCES CATEGORY(CategoryID) ON DELETE CASCADE
);
CREATE TABLE ENROLMENT (
    EnrolmentID VARCHAR(50) PRIMARY KEY,
    ParticipantID VARCHAR(50) NOT NULL,
    EventCategoryID VARCHAR(50) NOT NULL,
    EnrolmentDate DATETIME NOT NULL DEFAULT GETDATE(),
    Status VARCHAR(50) NOT NULL DEFAULT 'Registered',

    CONSTRAINT FK_Enrolment_Participant 
        FOREIGN KEY (ParticipantID) REFERENCES [USER](UserID),

    CONSTRAINT FK_Enrolment_EventCategory 
        FOREIGN KEY (EventCategoryID) REFERENCES EVENTCATEGORY(EventCategoryID)
);
