CREATE DATABASE RaceDayDB;
GO

USE RaceDayDB;
GO
DROP TABLE IF EXISTS RESULT;
DROP TABLE IF EXISTS ENROLMENT;
DROP TABLE IF EXISTS EVENTCATEGORY;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS [USER];
GO
